name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"  # Ensure Flutter SDK version is compatible

dependencies:
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.0
  url_launcher: ^6.1.10
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+2
  path_provider: ^2.1.1
  image_picker: ^0.8.6
  path: ^1.8.3
  permission_handler: ^11.0.1
  flutter_tts: ^3.6.3  # Text-to-speech
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0


  # Add other necessary dependencies here, such as image processing libraries
  # For YOLOv5 integration, you might need dependencies like 'flutter_tesseract_ocr' or 'provider'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Add the necessary assets section if you are using any custom assets
